print("pada tanggal 07 Juli 2025")
print("kau membuat diriku berharap lagi pada dunia")
print("kau membuat diriku percaya lagi pada cinta")
print("ku ingat pada dini hari jam 2:26 kau berkata ")
print("My Violet 💜: part P### kecintaan ma Adam")
print("Aku menjadi orang paling bahagia di dunia")
print("tapi kenapa kita jadi asing.....")
print("dan aku masih merindukanmu sampai sekarang")
print("bisakah kita berteman lagi?")
print("stelle,ran,han Dan adam masih membutuhkan mak/kakaknya....")
print("di hantui oleh bayanganmu yang selalu masih bersamaku di  mimpiku")
print("in another life kak p###?")